###
POST {{BASE_URL}}/auth/sign-in HTTP/1.1
content-type: application/json

{
    "email": "john.doe@email.com",
    "password": "123456"
}

###
POST {{BASE_URL}}/auth/sign-out HTTP/1.1
content-type: application/json

###
POST {{BASE_URL}}/auth/sign-up HTTP/1.1
content-type: application/json

{
    "cnpj": "12345678901237",
    "name": "Wayne Enterprises",
    "email": "john.doe@email.com",
    "fullName": "John Doe"
}

###
POST {{BASE_URL}}/auth/forget-password HTTP/1.1
content-type: application/json

{
    "email": "john.doe@email.com"
}

###
POST {{BASE_URL}}/auth/reset-password HTTP/1.1
content-type: application/json

{
    "password": "123456",
    "token": "your-token"
}