###
POST {{BACKEND_URL}}/auth/sign-in HTTP/1.1
content-type: application/json

{
    "email": "john.doe@email.com",
    "password": "Senha12345@"
}

###
POST {{BACKEND_URL}}/auth/sign-out HTTP/1.1
content-type: application/json

###
POST {{BACKEND_URL}}/auth/sign-up HTTP/1.1
content-type: application/json

{
    "cnpj": "12345678901237",
    "name": "Wayne Enterprises",
    "email": "john.doe@email.com",
    "fullName": "John Doe"
}

###
POST {{BACKEND_URL}}/auth/forget-password HTTP/1.1
content-type: application/json

{
    "email": "john.doe@email.com"
}

###
POST {{BACKEND_URL}}/auth/reset-password HTTP/1.1
content-type: application/json

{
    "password": "Senha12345@",
    "token": "your-token"
}