# @name auth_request
POST {{BASE_URL}}/auth/sign-in HTTP/1.1
content-type: application/json

{
    "email": "{{USERNAME}}",
    "password": "{{PASSWORD}}"
}

###

@token = {{auth_request.response.body.token}}