###
GET http://localhost:3000/task/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibWF0ZXVzIiwiaWF0IjoxNzM5NjM2OTIwLCJleHAiOjE3Mzk2NDA1MjB9.xzfZbwY54Ful-bjeTxhi2q-AelcDWQ9pJbEGOvzIw6o HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibWF0ZXVzIiwiaWF0IjoxNzM5NjM2OTIwLCJleHAiOjE3Mzk2NDA1MjB9.xzfZbwY54Ful-bjeTxhi2q-AelcDWQ9pJbEGOvzIw6o

###
GET http://localhost:3000/task?title=T HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibWF0ZXVzIiwiaWF0IjoxNzM5NjM2OTIwLCJleHAiOjE3Mzk2NDA1MjB9.xzfZbwY54Ful-bjeTxhi2q-AelcDWQ9pJbEGOvzIw6o

###
POST http://localhost:3000/task HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibWF0ZXVzIiwiaWF0IjoxNzM5NjM2OTIwLCJleHAiOjE3Mzk2NDA1MjB9.xzfZbwY54Ful-bjeTxhi2q-AelcDWQ9pJbEGOvzIw6o

{
    "title": "Task 01",
    "description": "Task 01",
    "expirationDate": "2024-01-01"
}

###
PUT http://localhost:3000/task/b4537ce0-be4e-480b-a900-43062a464783 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibWF0ZXVzIiwiaWF0IjoxNzM5NjM2OTIwLCJleHAiOjE3Mzk2NDA1MjB9.xzfZbwY54Ful-bjeTxhi2q-AelcDWQ9pJbEGOvzIw6o

{
    "description": "Task 02",
    "expirationDate": "2025-01-01",
    "title": "Task 02"
}

###
DELETE http://localhost:3000/task/b4537ce0-be4e-480b-a900-43062a464783 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoibWF0ZXVzIiwiaWF0IjoxNzM5NjM2OTIwLCJleHAiOjE3Mzk2NDA1MjB9.xzfZbwY54Ful-bjeTxhi2q-AelcDWQ9pJbEGOvzIw6o