###
POST {{BACKEND_URL}}/user HTTP/1.1
content-type: application/json

{
    "fullName": "John Doe",
    "email": "john.doe@email.com",
    "roleId": 1,
    "address": {
        "cep": "12345678",
        "number": "123"
    }
}

###
GET {{BACKEND_URL}}/user/1 HTTP/1.1
content-type: application/json

###
GET {{BACKEND_URL}}/profile HTTP/1.1
content-type: application/json

###
GET {{BACKEND_URL}}/user?page=1&fullName=john&orderBy=email&status=active HTTP/1.1
content-type: application/json

###
PATCH {{BACKEND_URL}}/user/1 HTTP/1.1
content-type: application/json

{
    "cpf": "11111111111"
}

###
PATCH {{BACKEND_URL}}/user/1 HTTP/1.1
content-type: application/json

{
    "address": {
        "cep": "12345676"
    }
}

###
PATCH {{BACKEND_URL}}/user/1 HTTP/1.1
content-type: application/json

{
    "isActive": true
}

###
PATCH {{BACKEND_URL}}/profile HTTP/1.1
content-type: application/json

{
    "fullName": "Jane Doe"
}

###
GET {{BACKEND_URL}}/permissions HTTP/1.1
content-type: application/json

###
DELETE {{BACKEND_URL}}/user/1 HTTP/1.1
content-type: application/json

{
    "isActive": true
}

###
GET {{BACKEND_URL}}/user/pdf?fullName=john&orderBy=email&status=active HTTP/1.1
content-type: application/json

###
GET {{BACKEND_URL}}/user/sheet?fullName=john&orderBy=email&status=active HTTP/1.1
content-type: application/json
