import { RoleType, Resources, Actions } from '@prisma/client';

export const rolePermissions: Record<
  RoleType,
  { resource: Resources; action: Actions }[]
> = {
  [RoleType.ADMIN]: [
    { resource: Resources.USERS, action: Actions.CREATE },
    { resource: Resources.USERS, action: Actions.READ },
    { resource: Resources.USERS, action: Actions.UPDATE },
    { resource: Resources.USERS, action: Actions.DELETE },
    { resource: Resources.VEHICLES, action: Actions.CREATE },
    { resource: Resources.VEHICLES, action: Actions.READ },
    { resource: Resources.VEHICLES, action: Actions.UPDATE },
    { resource: Resources.VEHICLES, action: Actions.DELETE },
    { resource: Resources.STORES, action: Actions.CREATE },
    { resource: Resources.STORES, action: Actions.READ },
    { resource: Resources.STORES, action: Actions.UPDATE },
    { resource: Resources.STORES, action: Actions.DELETE },
    { resource: Resources.VEHICLE_PURCHASE, action: Actions.READ },
    { resource: Resources.VEHICLE_PURCHASE, action: Actions.UPDATE },
    { resource: Resources.VEHICLE_SALE, action: Actions.READ },
    { resource: Resources.VEHICLE_SALE, action: Actions.UPDATE },
    { resource: Resources.VEHICLE_SALE, action: Actions.CREATE },
    { resource: Resources.VEHICLE_EXPENSE, action: Actions.CREATE },
    { resource: Resources.VEHICLE_EXPENSE, action: Actions.READ },
    { resource: Resources.VEHICLE_EXPENSE, action: Actions.UPDATE },
    { resource: Resources.VEHICLE_EXPENSE, action: Actions.DELETE },
    { resource: Resources.ACCOUNTS_PAYABLE, action: Actions.CREATE },
    { resource: Resources.ACCOUNTS_PAYABLE, action: Actions.READ },
    { resource: Resources.ACCOUNTS_PAYABLE, action: Actions.UPDATE },
    { resource: Resources.ACCOUNTS_PAYABLE, action: Actions.DELETE },
    { resource: Resources.ACCOUNTS_RECEIVABLE, action: Actions.CREATE },
    { resource: Resources.ACCOUNTS_RECEIVABLE, action: Actions.READ },
    { resource: Resources.ACCOUNTS_RECEIVABLE, action: Actions.UPDATE },
    { resource: Resources.ACCOUNTS_RECEIVABLE, action: Actions.DELETE },
    { resource: Resources.CUSTOMERS, action: Actions.CREATE },
    { resource: Resources.CUSTOMERS, action: Actions.READ },
    { resource: Resources.CUSTOMERS, action: Actions.UPDATE },
    { resource: Resources.CUSTOMERS, action: Actions.DELETE },
  ],
  [RoleType.SELLER]: [
    { resource: Resources.VEHICLES, action: Actions.READ },
    { resource: Resources.VEHICLE_SALE, action: Actions.READ },
    { resource: Resources.VEHICLE_SALE, action: Actions.UPDATE },
    { resource: Resources.VEHICLE_SALE, action: Actions.CREATE },
    { resource: Resources.CUSTOMERS, action: Actions.CREATE },
    { resource: Resources.CUSTOMERS, action: Actions.READ },
    { resource: Resources.CUSTOMERS, action: Actions.UPDATE },
  ],
};
