export const colors = [
  { label: "Branco", value: "FFFFFF" },
  { label: "Branco Pérola", value: "F8F8FF" },
  { label: "Preto", value: "000000" },
  { label: "Preto Metálico", value: "0A0A0A" },
  { label: "Prata", value: "C0C0C0" },
  { label: "Prata Lunar", value: "D9D9D9" },
  { label: "Cinza", value: "808080" },
  { label: "Cinza Chumbo", value: "505050" },
  { label: "Cinza Grafite", value: "4B4B4B" },
  { label: "Azul", value: "0000FF" },
  { label: "Azul Claro", value: "87CEFA" },
  { label: "Azul Céu", value: "ADD8E6" },
  { label: "Azul Escuro", value: "00008B" },
  { label: "Azul Marinho", value: "000080" },
  { label: "Azul Metálico", value: "4169E1" },
  { label: "Azul Petróleo", value: "355E66" },
  { label: "Verde", value: "008000" },
  { label: "Verde Claro", value: "90EE90" },
  { label: "Verde Escuro", value: "006400" },
  { label: "Verde Bandeira", value: "009739" },
  { label: "Verde Esmeralda", value: "50C878" },
  { label: "Verde Oliva", value: "808000" },
  { label: "Amarelo", value: "FFFF00" },
  { label: "Laranja", value: "FFA500" },
  { label: "Laranja Metálico", value: "FF8C00" },
  { label: "Vermelho", value: "FF0000" },
  { label: "Vermelho Escuro", value: "8B0000" },
  { label: "Vermelho Cereja", value: "D2042D" },
  { label: "Vermelho Ferrari", value: "FF2800" },
  { label: "Vermelho Borgonha", value: "800020" },
  { label: "Roxo", value: "800080" },
  { label: "Violeta", value: "8A2BE2" },
  { label: "Lilás", value: "C8A2C8" },
  { label: "Rosa", value: "FFC0CB" },
  { label: "Rosa Choque", value: "FF69B4" },
  { label: "Marrom", value: "8B4513" },
  { label: "Marrom Claro", value: "A0522D" },
  { label: "Bronze", value: "CD7F32" },
  { label: "Cobre", value: "B87333" },
  { label: "Dourado", value: "FFD700" },
  { label: "Champagne", value: "F7E7CE" },
  { label: "Bege", value: "F5F5DC" },
  { label: "Creme", value: "FFFDD0" },
  { label: "Salmão", value: "FA8072" },
  { label: "Azul Tiffany", value: "81D8D0" },
  { label: "Turquesa", value: "40E0D0" },
  { label: "Verde Menta", value: "98FF98" },
  { label: "Grafite Metálico", value: "3B3B3B" },
  { label: "Cinza Prata", value: "B2B2B2" },
];
