### FETCH Users
GET http://localhost:8000/users HTTP/1.1
content-type: application/json

### GET Users
GET http://localhost:8000/users/2 HTTP/1.1
content-type: application/json

### POST Users
POST http://localhost:8000/users HTTP/1.1
content-type: application/json

{
    "name": "Mateus Pitura",
    "age": 20
}

### DELETE Users
DELETE http://localhost:8000/users/1 HTTP/1.1
content-type: application/json

### UPDATE Users
PUT http://localhost:8000/users/2 HTTP/1.1
content-type: application/json

{
    "name": "Mateus Pitura"
}